
import type { Metadata } from 'next'
import { Noto_Sans } from 'next/font/google'
import { Footer, Header, Sidebar } from './components'
import './globals.css'
import styles from './layout.module.css'

const noto_sans = Noto_Sans({ 
  weight: ['300','400','500','700'],
  style: ['normal'],
  subsets: ['latin'], 
  display: 'swap'}) 

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru">
      <body className={noto_sans.className}>
        <div className={styles.wrapper}>
          <Header className={styles.header}/>
          <Sidebar className={styles.sidebar}/>
          <main className={styles.main}>{children}</main>
          <Footer className={styles.footer}/>
        </div>
      </body>
    </html>
  )
}
